export const GET_DATA_FETCHING = 'GET_DATA_FETCHING';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_SEARCH_FETCHING = 'GET_SEARCH_FETCHING';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_RECOMMENDATIONS_FETCHING = 'GET_RECOMMENDATIONS_FETCHING';
export const GET_RECOMMENDATIONS_SUCCESS = 'GET_RECOMMENDATIONS_SUCCESS';
